# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-facebook-practice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-facebook-practice
  pod 'FacebookCore'  
  pod 'FacebookLogin'
  pod ‘ObjectMapper’

  target 'ios-facebook-practiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-facebook-practiceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
