# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '01_Realm_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'

  # Pods for 01_Realm_Swift

  target '01_Realm_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '01_Realm_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
