# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flickr-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flickr-demo
  pod 'Alamofire'
  pod 'ObjectMapper'

  target 'flickr-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flickr-demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
