# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-weather-api-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-weather-api-demo
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'STV-Extensions'
  pod 'SVProgressHUD'
  

  target 'ios-weather-api-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-weather-api-demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
